# Defaults
defaults: {}

branches:
  - match: 'melt-radar-totem-local'
    realms:
      - realm: 'local'
        proxy:
          - host: 'radar.totem.local'
            paths:
              - path: '/'
                port: 8080
        comptroller:
          command: start