# Defaults
defaults: {}

branches:
  - match: 'melt-radar'
    realms:
      - realm: 'not-production'
        proxy:
          - host: 'radar.cu.melt.sh'
            paths:
              - path: '/'
                port: 8080
        comptroller:
          command: start